# Generated by Django 4.2.19 on 2025-02-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('pending_orders', models.IntegerField(default=0)),
                ('processing_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('average_processing_time', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Metrics',
                'verbose_name_plural': 'Order Metrics',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('user_id', models.CharField(max_length=100)),
                ('_item_ids', models.TextField(db_column='item_ids')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_start_time', models.DateTimeField(blank=True, null=True)),
                ('processing_end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'), models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx')],
            },
        ),
    ]
