# Generated by Django 4.2.19 on 2025-02-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='_item_ids',
            field=models.TextField(db_column='item_ids', default='[]'),
        ),
    ]
